#if !defined(TEST_HAS_MEMBER_DATA_HPP)
#define TEST_HAS_MEMBER_DATA_HPP

#include "test_structs.hpp"
#include <boost/tti/member_data.hpp>

BOOST_TTI_HAS_MEMBER_DATA(AnInt)
BOOST_TTI_HAS_MEMBER_DATA(aMember)
BOOST_TTI_TRAIT_HAS_MEMBER_DATA(CMember,cMem)
BOOST_TTI_HAS_MEMBER_DATA(someDataMember)
BOOST_TTI_HAS_MEMBER_DATA(IntBT)
BOOST_TTI_TRAIT_HAS_MEMBER_DATA(NestedData,NestedCT)
BOOST_TTI_TRAIT_HAS_MEMBER_DATA(AOther,OtherAT)
BOOST_TTI_HAS_MEMBER_DATA(ONestStr)

#endif // TEST_HAS_MEMBER_DATA_HPP
