#if !defined(TEST_MF_HAS_MEMBER_DATA_HPP)
#define TEST_MF_HAS_MEMBER_DATA_HPP

#include "TestStructs.hpp"
#include <boost/tti/TTIntrospection.hpp>

TTI_HAS_MEMBER(AnInt)
TTI_HAS_MEMBER(aMember)
TTI_TRAIT_HAS_MEMBER(CMember,cMem)
TTI_HAS_MEMBER(someDataMember)
TTI_HAS_MEMBER(IntBT)
TTI_TRAIT_HAS_MEMBER(NestedData,NestedCT)
TTI_TRAIT_HAS_MEMBER(AOther,OtherAT)
TTI_HAS_MEMBER(ONestStr)
TTI_MEMBER_TYPE(BType)
TTI_MEMBER_TYPE(CType)
TTI_MEMBER_TYPE(AStructType)

#endif // TEST_MF_HAS_MEMBER_DATA_HPP
